export const AUTH_USER = "AUTH_USER";
export const AUTH_ERROR = "AUTH_ERROR";

export const FETCHING_BOOKS = "FETCHING_BOOKS";
export const FETCHING_BOOKS_SUCCESS = "FETCHING_BOOKS_SUCCESS";
export const FETCHING_BOOKS_ERROR = "FETCHING_BOOKS_ERROR";
export const FETCHING_BOOK = "FETCHING_BOOK";
export const FETCHING_BOOK_SUCCESS = "FETCHING_BOOK_SUCCESS";
export const FETCHING_BOOK_ERROR = "FETCHING_BOOK_ERROR";

export const CATEGORY_CREATE = "CATEGORY_CREATE";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_ERROR = "CATEGORY_CREATE_ERROR";
export const FETCHING_CATEGORIES = "FETCHING_CATEGORIES";
export const FETCHING_CATEGORIES_SUCCESS = "FETCHING_CATEGORIES_SUCCESS";
export const FETCHING_CATEGORIES_ERROR = "FETCHING_CATEGORIES_ERROR";
export const CATEGORY_DELETE = "CATEGORY_DELETE";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_ERROR = "CATEGORY_DELETE_ERROR";
export const CATEGORY_EDIT = "CATEGORY_EDIT";
export const CATEGORY_EDIT_SUCCESS = "CATEGORY_EDIT_SUCCESS";
export const CATEGORY_EDIT_ERROR = "CATEGORY_EDIT_ERROR";
