export const AUTH_USER = "AUTH_USER";
export const AUTH_ERROR = "AUTH_ERROR";

export const FETCHING_BOOKS = "FETCHING_BOOKS";
export const FETCHING_BOOKS_SUCCESS = "FETCHING_BOOKS_SUCCESS";
export const FETCHING_BOOKS_ERROR = "FETCHING_BOOKS_ERROR";

export const FETCHING_BOOK = "FETCHING_BOOK";
export const FETCHING_BOOK_SUCCESS = "FETCHING_BOOK_SUCCESS";
export const FETCHING_BOOK_ERROR = "FETCHING_BOOK_ERROR";

export const CATEGORY_CREATE = "CATEGORY_CREATE";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_ERROR = "CATEGORY_CREATE_ERROR";
